import test from "node:test";
import assert from "node:assert/strict";
import { evidenceFromHTML, reextract, validateRecipe } from "./extraction.ts";
import { createTranslationPipeline, validateCompilation } from "./compiler.ts";
import { createAstraModelTransport, createAstraExplorationPlanner } from "./astra.ts";
import { createBrowserCaptureTransport } from "./browser.ts";
import { createCloudAccessGate, CATALOG_ID, type ModelTransport } from "./types.ts";
import { isPublicIPAddress, normalizePublicURL, validatePublicURL } from "./url-policy.ts";
import type { Browser } from "@cloudflare/puppeteer";

// All inputs/model outputs in this file are synthetic local test fixtures.
// They are not showcases and were not generated by Astra.
const fixtureHTML = (price = "$123.45", extra = "") => `<html><head><title>Local Fixture Finance</title><meta name="theme-color" content="#6040aa"></head><body><h1>Local Fixture Finance</h1><p>This synthetic local test fixture contains invented quotes for automated verification only.</p><ul>${extra}<li class="quote" data-symbol="ALPHA"><a href="/quote/ALPHA">Alpha</a><span class="price">${price}</span></li><li class="quote" data-symbol="BETA"><a href="/quote/BETA">Beta</a><span class="price">$91.02</span></li></ul></body></html>`;
const evidence = () => evidenceFromHTML(fixtureHTML(), "https://fixture.example.com/finance");
const output = () => ({
  theme: { primaryColor: "#6040aa" },
  components: [
    { id: "root", component: "Column", children: ["heading", "quotes"], align: "stretch", justify: "start" },
    { id: "heading", component: "Text", text: { path: "/content/fields/title" }, variant: "h1" },
    { id: "quotes", component: "Column", children: { componentId: "quote", path: "/content/lists/quotes" }, align: "stretch", justify: "start" },
    { id: "quote", component: "Row", children: ["link", "price"], align: "center", justify: "spaceBetween" },
    { id: "link", component: "Button", child: "name", action: { event: { name: "openURL", context: { url: { path: "url" } } } } },
    { id: "name", component: "Text", text: { path: "name" }, variant: "body" },
    { id: "price", component: "Text", text: { path: "price" }, variant: "body" },
  ],
  recipe: {
    version: 1,
    fields: [{ key: "title", selector: "h1", value: "text", required: true }],
    lists: [{ key: "quotes", selector: ".quote", keyAttribute: "data-symbol", maxItems: 60, fields: [
      { key: "name", selector: "a", value: "text", required: true },
      { key: "url", selector: "a", value: "href", required: true },
      { key: "price", selector: ".price", value: "text", required: true },
    ] }],
  },
});

test("fixture content updates preserve source strings and stable IDs without changing specification", () => {
  const first = validateCompilation(output(), evidence());
  const nextEvidence = evidenceFromHTML(fixtureHTML("-$124.10", '<li class="quote" data-symbol="NEW"><a href="/quote/NEW">New</a><span class="price">$42.00</span></li>'), evidence().sourceURL);
  const updated = reextract(nextEvidence, first.recipe);
  const before = (first.content.lists as { quotes: Record<string, string>[] }).quotes;
  const after = (updated.lists as { quotes: Record<string, string>[] }).quotes;
  assert.equal(after[1]?.price, "-$124.10");
  assert.equal(before[0]?.id, after[1]?.id);
  assert.equal(after[1]?.url, "https://fixture.example.com/quote/ALPHA");
  assert.equal(first.spec.catalogId, CATALOG_ID);
  assert.deepEqual(first.spec.messages.map(m => m.version), ["v0.9", "v0.9"]);
  assert.ok(!JSON.stringify(first.spec).includes("$123.45"));
});

test("recipe drift fails instead of publishing empty or fabricated required values", () => {
  const broken = evidenceFromHTML(fixtureHTML().replaceAll('class="price"', 'class="changed"'), evidence().sourceURL);
  assert.throws(() => reextract(broken, output().recipe), { code: "RECIPE_DRIFT" });
  assert.throws(() => validateRecipe({ ...output().recipe, fields: [{ key: "constructor", selector: "h1", value: "text", required: true }] }), { code: "INVALID_RECIPE" });
});

test("unsafe source URLs and mixed public/private DNS fail closed", async () => {
  for (const url of ["http://localhost", "http://127.1", "http://0x7f000001", "http://169.254.169.254", "http://10.0.0.1", "https://x.local", "https://user:password@example.com", "file:///tmp/file"]) assert.throws(() => normalizePublicURL(url));
  assert.equal(isPublicIPAddress("2001:4860:4860::8888"), true);
  assert.equal(isPublicIPAddress("2001:db8::1"), false);
  assert.equal(isPublicIPAddress("::ffff:127.0.0.1"), false);
  await assert.rejects(validatePublicURL("https://fixture.example.com", async () => ["8.8.8.8", "10.1.2.3"]), { code: "UNSAFE_DNS" });
  assert.equal((await validatePublicURL("https://fixture.example.com/a?x=1#section", async () => ["8.8.8.8"])).href, "https://fixture.example.com/a?x=1");
});

test("relative media/links become absolute and private or script schemes never survive extraction", () => {
  const raw = evidenceFromHTML('<html><body><a href="javascript:alert(1)">Bad</a><img src="../logo.png"><h1>Fixture</h1></body></html>', "https://fixture.example.com/a/b");
  const content = reextract(raw, { version: 1, fields: [{ key: "url", selector: "a", value: "href", required: false }, { key: "image", selector: "img", value: "src", required: true }], lists: [] });
  assert.deepEqual(content.fields, { url: "", image: "https://fixture.example.com/logo.png" });
});

test("large raw script payload is stripped before the smaller evidence cap", () => {
  const raw = evidenceFromHTML(`<html><head><script>${"x".repeat(2_100_000)}</script></head><body><h1>Fixture</h1></body></html>`, evidence().sourceURL);
  assert.ok(raw.html.length < 200);
  assert.equal(raw.html.includes("script"), false);
});

test("unsupported actions, cycles, missing refs, unbound values and wrong URL fields reject", () => {
  const variants: unknown[] = [];
  const cyclic = output(); cyclic.components[0]!.children = ["root"]; variants.push(cyclic);
  const missing = output(); missing.components[0]!.children = ["absent"]; variants.push(missing);
  const literal = JSON.parse(JSON.stringify(output())); literal.components[1].text = "Invented headline"; variants.push(literal);
  const action = JSON.parse(JSON.stringify(output())); action.components[4].action.event.name = "deleteAccount"; variants.push(action);
  const wrongURL = JSON.parse(JSON.stringify(output())); wrongURL.components[4].action.event.context.url.path = "name"; variants.push(wrongURL);
  for (const variant of variants) assert.throws(() => validateCompilation(variant, evidence()), { code: "INVALID_SPEC" });
});

test("compiler performs at most one repair and uses model provenance from transport", async () => {
  let calls = 0;
  const model: ModelTransport = { async generate() { calls++; return { value: calls === 1 ? {} : output(), model: "fixture-mock-not-Astra" }; } };
  const pipeline = createTranslationPipeline({ captureTransport: { async capture() { return evidence(); } }, modelTransport: model });
  const result = await pipeline.compile(evidence());
  assert.equal(calls, 2);
  assert.equal(result.generation.model, "fixture-mock-not-Astra");
  let failures = 0;
  const bad = createTranslationPipeline({ captureTransport: { async capture() { return evidence(); } }, modelTransport: { async generate() { failures++; return { value: {}, model: "fixture" }; } } });
  await assert.rejects(bad.compile(evidence()), { code: "INVALID_SPEC" });
  assert.equal(failures, 2);
});

test("reextract remains model-free and capture forwards refresh purpose", async () => {
  let purpose: string | undefined;
  const pipeline = createTranslationPipeline({ captureTransport: { async capture(_url, options) { purpose = options.purpose; return evidence(); } }, modelTransport: { async generate() { throw new Error("Model must not be called"); } } });
  const captured = await pipeline.capture(evidence().sourceURL, { purpose: "revalidate" });
  assert.equal(purpose, "revalidate");
  assert.equal((pipeline.reextract(captured, output().recipe).fields as { title: string }).title, "Local Fixture Finance");
});

test("cloud gate blocks before browser or model transport invocation", async () => {
  let cloudCalls = 0;
  const browser = createBrowserCaptureTransport({ fetch: async () => { cloudCalls++; return new Response(); } });
  await assert.rejects(browser.capture(new URL(evidence().sourceURL), { deadlineAt: Date.now() + 1000 }), { code: "CLOUD_APPROVAL_REQUIRED" });
  const model = createAstraModelTransport({ gateway() { cloudCalls++; throw new Error("Cloud access must be gated"); } }, { gatewayID: "fixture" });
  await assert.rejects(model.generate({ instructions: "fixture", input: "fixture", schema: {}, maxOutputTokens: 1, signal: new AbortController().signal }), { code: "CLOUD_APPROVAL_REQUIRED" });
  assert.equal(cloudCalls, 0);
});

test("injected AI adapter uses native Responses binding with exact Astra and low effort schema", async () => {
  let sent: Record<string, unknown> = {};
  const signal = new AbortController().signal;
  const model = createAstraModelTransport({ gateway(id) {
    assert.equal(id, "fixture");
    return { async run(request, options) {
      assert.equal(request.provider, "openai");
      assert.equal(request.endpoint, "responses");
      assert.deepEqual(request.headers, { "Content-Type": "application/json" });
      assert.deepEqual(options?.extraHeaders, { "cf-aig-byok-alias": "fixture-alias" });
      assert.deepEqual(options?.gateway, { skipCache: true, retries: { maxAttempts: 1 } });
      assert.equal(options?.signal, signal);
      sent = request.query;
      return Response.json({ model: "gpt-6-astra", status: "completed", output_text: JSON.stringify({ fixture: true }) });
    } };
  } }, { gatewayID: "fixture", byokAlias: "fixture-alias", gate: createCloudAccessGate(true) });
  const result = await model.generate({ instructions: "fixture", input: "fixture", schema: {}, maxOutputTokens: 20, signal });
  assert.deepEqual(result.value, { fixture: true });
  assert.equal(sent.model, "gpt-6-astra");
  assert.deepEqual(sent.reasoning, { effort: "low" });
  assert.deepEqual(sent.text, { format: { type: "json_schema", name: "astrabrowse_output", strict: true, schema: {} } });
  assert.equal(sent.store, false);
  const wrong = createAstraModelTransport({ gateway() { return { async run() { return { model: "gpt-other", output_text: "{}" }; } }; } }, { gatewayID: "fixture", gate: createCloudAccessGate(true) });
  await assert.rejects(wrong.generate({ instructions: "", input: "", schema: {}, maxOutputTokens: 1, signal: new AbortController().signal }), { code: "MODEL_MISMATCH" });
});

test("cancellation and an expired total deadline stop compilation", async () => {
  const controller = new AbortController();
  const pipeline = createTranslationPipeline({ captureTransport: { async capture() { return new Promise(() => {}); } }, modelTransport: { async generate() { throw new Error("must not run"); } } });
  const pending = pipeline.capture(evidence().sourceURL, { signal: controller.signal });
  controller.abort();
  await assert.rejects(pending);
  await assert.rejects(pipeline.compile({ ...evidence(), deadlineAt: Date.now() - 1 }), { code: "DEADLINE_EXCEEDED" });
});

test("Astra exploration cannot request off-origin or arbitrary browser actions", async () => {
  const planner = createAstraExplorationPlanner({ async generate() { return { model: "fixture", value: { actions: [{ kind: "open", amount: null, url: "https://evil.example.com" }] } }; } });
  await assert.rejects(planner(evidence(), new AbortController().signal), { code: "INVALID_EXPLORATION" });
});

test("injected browser adapter closes its session and skips exploration during revalidation", async () => {
  let closes = 0; let explores = 0; let currentURL = evidence().sourceURL;
  const progress: string[] = [];
  const page = {
    async setViewport() {}, async setBypassServiceWorker() {}, async setRequestInterception() {}, on() {}, async evaluateOnNewDocument() {}, async waitForFunction() {},
    async goto(url: string) { currentURL = url; return { ok: () => true }; }, url: () => currentURL,
    async content() { return fixtureHTML(); }, async createCDPSession() { return { async send() { return { devtoolsFrontendUrl: "https://viewer.example.com/fixture-only" }; } }; },
  };
  const browser = { async close() { closes++; }, async createBrowserContext() { return { async newPage() { return page; } }; } } as unknown as Browser;
  const transport = createBrowserCaptureTransport({ fetch: async () => { throw new Error("No remote requests permitted in fixture test"); } }, {
    gate: createCloudAccessGate(true), resolveDNS: async () => ["8.8.8.8"], launchBrowser: async () => browser,
    explore: async () => { explores++; return []; },
  });
  const captured = await transport.capture(new URL(currentURL), { purpose: "revalidate", deadlineAt: Date.now() + 90_000, onProgress(event) { if (event.type === "status") progress.push(event.stage); } });
  assert.equal(explores, 0);
  assert.equal(closes, 1);
  assert.equal(progress.at(-1), "captured");
  assert.deepEqual(captured.captureProfile, { id: "public-desktop-v1", viewport: { width: 1280, height: 900 } });
});

test("browser cleanup failure is not reported as successful capture", async () => {
  const browser = { async close() { throw new Error("fixture cleanup failure"); }, async createBrowserContext() { throw new Error("fixture capture failure"); } } as unknown as Browser;
  const transport = createBrowserCaptureTransport({ fetch: async () => new Response() }, { gate: createCloudAccessGate(true), resolveDNS: async () => ["8.8.8.8"], launchBrowser: async () => browser });
  await assert.rejects(transport.capture(new URL(evidence().sourceURL), { deadlineAt: Date.now() + 90_000 }), { code: "BROWSER_CLEANUP_FAILED" });
});

test("upstream errors expose safe diagnostic codes but never raw provider messages", async () => {
  const model = createAstraModelTransport({ gateway() { return { async run() { return Response.json({ error: { code: "invalid_json_schema", param: "text.format.schema", message: "SENSITIVE_FIXTURE_DO_NOT_EXPOSE" } }, { status: 400 }); } }; } }, { gatewayID: "fixture", gate: createCloudAccessGate(true) });
  await assert.rejects(model.generate({ instructions: "", input: "", schema: {}, maxOutputTokens: 1, signal: new AbortController().signal }), error => {
    assert.ok(error instanceof Error);
    assert.match(error.message, /invalid_json_schema/);
    assert.match(error.message, /text\.format\.schema/);
    assert.ok(!error.message.includes("SENSITIVE_FIXTURE_DO_NOT_EXPOSE"));
    return true;
  });
});
